### ISSUE TITLE
Oprava pluginu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-fio-bank-transactions#25]
Hází mi to tuhle chybu....

Warning: include(/home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/../../src/Services/Services.php): failed to open stream: No such file or directory in /home/vu008538/www/wp-content/plugins/google-calendar-events/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/../../src/Services/Services.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /home/vu008538/www/wp-content/plugins/google-calendar-events/vendor/composer/ClassLoader.php on line 444

Fatal error: Uncaught Error: Class 'FioTransactions\Services\Services' not found in /home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php:56 Stack trace: #0 /home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php(44): FioTransactions\FioTransactions->init() #1 /home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php(140): FioTransactions\FioTransactions->__construct() #2 /home/vu008538/www/wp-admin/includes/plugin.php(2300): include('/home/vu008538/...') #3 /home/vu008538/www/wp-admin/plugins.php(191): plugin_sandbox_scrape() #4 {main} thrown in /home/vu008538/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php on line 56

**Comment by kalich5** [comment]
Warning: require(/home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php): Failed to open stream: No such file or directory in /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/autoload_real.php on line 62

Fatal error: Uncaught Error: Failed opening required '/home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/autoload_real.php:62 Stack trace: #0 /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/autoload_real.php(52): composerRequiref3a39391535899232b6f136bfafc1c0a() #1 /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/autoload.php(7): ComposerAutoloaderInitf3a39391535899232b6f136bfafc1c0a::getLoader() #2 /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php(42): require('...') #3 /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/fio-transactions.php(140): FioTransactions\FioTransactions->__construct() #4 /home/vu009447/www/wp-admin/includes/plugin.php(2300): include('...') #5 /home/vu009447/www/wp-admin/plugins.php(191): plugin_sandbox_scrape() #6 {main} thrown in /home/vu009447/www/wp-content/plugins/skaut-fio-bank-transactions/vendor/composer/autoload_real.php on line 62
